name: push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test-on-call.yaml
    permissions:
      contents: read
      id-token: write  # required for Codecov OIDC in unit job
